#!/bin/bash
echo "starting program at $(date)"#date会被替换成日期和时间
echo "running program $0 with $# arguments with pid $$"
for file in "$@"; do
	grep foobar "$file" > /dev/null 2> /dev/ null
	#如果模式没有找到，则grep退出状态为1
  #我们将标准输出流和标准错误流重定向到null，因为我们并不关系这些信息
	if [[ $? -ne 0 ]]; then
		echo "File $file does not have any foobar,adding one"
		echo "# foobar" >> "$file"
	fi
done
